server:
  port: 9090

spring:
  data:
    mongodb:
      host: ${EtsTurHost}
      port: 27017
      database: EtsTurDB
      username: burcuser
      password: root
  mail:
    username: ${mail-service-username}
    password: ${mail-service-password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


